# Generated by Django 3.0.8 on 2020-07-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddt', '0002_remove_usecases_use_case_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrations',
            name='integration_id',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='kb_id',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='tool_id',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topic_id',
        ),
    ]
